Create Sport Model
bounswe/2021SpringGroup6 pull request #81
Opened 2021-06-06 16:12 UTC by fileames

Sport id-name will be stored on database

2021-06-07 20:45 UTC, eye-78 requested changes
please edit base.html file in an appropriate way
all other work is nice

2021-06-07 23:00 UTC, berkatil requested changes

2021-06-08 05:12 UTC, fileames commented on practice-app/website/api/sport.py
> +        return jsonify({"error":"Service unavailable"}), 403
Yes, you are right, I will correct it.

2021-06-08 05:35 UTC, fileames commented on practice-app/website/api/sport.py
> +        result = get_sport_by_keyword(sports, keyword)
Since I wanted to create unit tests for this part, I wanted to have a part without a database connection.

2021-06-08 06:00 UTC, berkatil commented on practice-app/website/api/sport.py
> +        result = get_sport_by_keyword(sports, keyword)
okay then.

2021-06-08 12:00 UTC, MercerFrey reviewed
Looks fine. I think it is ready to be merged.

2021-06-08 12:00 UTC, MercerFrey commented on practice-app/website/test/sport_test.py
> +
This tests looks fine. I will try to write some tests like this for my part.

2021-06-08 15:12 UTC, merged